### PR TITLE
Added Sorting algorithms in C++

### PR DESCRIPTION
**Pull request by saiharsha-22**
### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/larissalages/code_problems/blob/master/CONTRIBUTING.md) to this repository.

- [x] Make sure your files are in the right folder!
- [x] Make sure you add the extension of the file (.cpp, .python, .java, etc).
- [x] If your code is a solution for a code problem, please tell which one.
- [x] Make sure your code is working, test for a lot of cases.

### Description
Please describe your pull request.

:heart: Thank you!

I have added: quick sort, Selection sort and Shell sort.
solved issue #92

### CODE REVIEW

**Review by larissalages — CHANGES_REQUESTED** [review]
Thanks for the contribution! Could you move the files to classical_algorithms/c++/ ?

**Comment by saiharsha-22** [comment]
@larissalages yeah sure I will move the algorithms and send the pull request again

**Review by saiharsha-22 — COMMENTED** [review]
I have added the shell  sort in the classic algorithms and removed the repetition of the quick  sort algorithm in c++

**Comment by saiharsha-22** [comment]
@larissalages I have made the changes can you please check it once.

**Review by larissalages — APPROVED** [review]

**Pull request merged**
