### PR TITLE
solved Hotel Prices question in Hackerrank and Created Hotel_Prices.cpp in code_problems/Hackerrank/c++/Hotel_Prices.cpp

### PR DESCRIPTION
**Pull request by Deepthi2001**
Added Hotel_Prices.cpp

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/larissalages/code_problems/blob/master/CONTRIBUTING.md) to this repository.

- [ ] Make sure your files are in the right folder!
- [ ] Make sure you add the extension of the file (.cpp, .python, .java, etc).
- [ ] If your code is a solution for a code problem, please tell which one.
- [ ] Make sure your code is working, test for a lot of cases.

### Description
Please describe your pull request.

:heart: Thank you!

### CODE REVIEW

**Review by larissalages — APPROVED** [review]

**Review by larissalages — CHANGES_REQUESTED** [review]
Can you solve the conflits with master? then I can merge, thanks!

**Comment by Deepthi2001** [comment]
> Can you solve the conflits with master? then I can merge, thanks!

what is the issue with the master?

**Comment by larissalages** [comment]
> > Can you solve the conflits with master? then I can merge, thanks!
> 
> what is the issue with the master?

This branch has conflicts that must be resolved
Use the web editor or the  to resolve conflicts.
Conflicting files
leetcode/cpp/Array/56.cpp

**Comment by Deepthi2001** [comment]
@larissalages I have added question links and commented time and space complexity to all the codes.please comment if any issues. Thankyou!

**Comment by Deepthi2001** [comment]
@larissalages Can you please look into this and update me the issue I have submitted one hackerrank solution and solutions to 4 leetcode problems.I dont know why the merging is blocked .Thankyou!

**Comment by Deepthi2001** [comment]
> > > Can you solve the conflits with master? then I can merge, thanks!
> > 
> > 
> > what is the issue with the master?
> 
> This branch has conflicts that must be resolved
> Use the web editor or the to resolve conflicts.
> Conflicting files
> leetcode/cpp/Array/56.cpp

@larissalages Okay, I'm sorry I got the error. I think 56.cpp is already present in the previous repository and yes now I have deleted the file 56.cpp I think it is fine now. Please do check and merge if no issues.Thankyou!

**Review by larissalages — APPROVED** [review]

**Comment by larissalages** [comment]
> > > > Can you solve the conflits with master? then I can merge, thanks!
> > > 
> > > 
> > > what is the issue with the master?
> > 
> > 
> > This branch has conflicts that must be resolved
> > Use the web editor or the to resolve conflicts.
> > Conflicting files
> > leetcode/cpp/Array/56.cpp
> 
> @larissalages Okay, I'm sorry I got the error. I think 56.cpp is already present in the previous repository and yes now I have deleted the file 56.cpp I think it is fine now. Please do check and merge if no issues.Thankyou!

It is perfect now, thanks!!

**Pull request merged**
