### PR TITLE
Create 189. Rotate Array.cpp

### PR DESCRIPTION
**Pull request by SouravCodery**
**Implemented the LeetCode's "189 Rotate Array" Problem using C++. The Solution is well commented and formatted. The Solution has been accepted by LeetCode's Judge.**

Link to the problem:
[189. Rotate Array.cpp](https://leetcode.com/problems/rotate-array/)

### Your checklist for this pull request
🚨Please review the [guidelines for contributing](https://github.com/larissalages/code_problems/blob/master/CONTRIBUTING.md) to this repository.

- [Done] Make sure your files are in the right folder!
- [Done] Make sure you add the extension of the file (.cpp, .python, .java, etc).
- [Done ] If your code is a solution for a code problem, please tell which one.
- [Done ] Make sure your code is working, test for a lot of cases.

### Description
Please describe your pull request.

:heart: Thank you!

### CODE REVIEW

**Review by larissalages — CHANGES_REQUESTED** [review]
can you rename the file to 189_rotate_array.cpp?

**Review by SouravCodery — COMMENTED** [review]
Changed the Name to 189_rotate_array.cpp

**Comment by SouravCodery** [comment]
> can you rename the file to 189_rotate_array.cpp?

Done Sir!

**Review by SouravCodery — COMMENTED** [review]
Changed Name to 189_rotate_array.cpp

**Review by larissalages — APPROVED** [review]

**Pull request merged**
